### ISSUE TITLE
numbers with dots but no decimal part crash pakettic

### ISSUE THREAD

**Issue by sknebel** [vsariola/pakettic#8]
The following cart crashes pakettic:
```

t=0.

function TIC()
end
```

I'm not entirely sure if Lua is formally expected to allow this syntax, but TIC-80 does accept it. (It's also pointless to write, but I did by accident and was confused by the crash)

**Comment by vsariola** [comment]
Well, LUA 5.3 manual just tries to describe what LUA does, and based on the manual, it's actually not quite clear what the behavior should be :) But since LUA 5.3 allows it we have to allow it too!

Fixed. While waiting for a new version release, you can test the fix with:

```
$ pip install git+https://github.com/vsariola/pakettic.git@main
```
